import { useTranslation } from "react-i18next";

export function useRecipeData() {
  const { t } = useTranslation();

  const recipes = [
    {
      id: 1,
      title: t("recipes.risotto.title"),
      description: t("recipes.risotto.description"),
      image:
        "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400&h=300&fit=crop&crop=center",
      time: t("recipes.risotto.time"),
      servings: t("recipes.risotto.servings"),
      difficulty: t("recipes.risotto.difficulty"),
      tags: [
        t("recipes.tags.italian"),
        t("recipes.tags.creamy"),
        t("recipes.tags.protein"),
      ],
      date: t("recipes.date.today"),
      rating: 5,
      ingredients: [
        t("recipes.risotto.ingredients.rice"),
        t("recipes.risotto.ingredients.chicken"),
        t("recipes.risotto.ingredients.broth"),
        t("recipes.risotto.ingredients.onion"),
        t("recipes.risotto.ingredients.garlic"),
        t("recipes.risotto.ingredients.wine"),
        t("recipes.risotto.ingredients.lemon"),
        t("recipes.risotto.ingredients.lemon_zest"),
        t("recipes.risotto.ingredients.parmesan"),
        t("recipes.risotto.ingredients.butter"),
        t("recipes.risotto.ingredients.herbs"),
        t("recipes.risotto.ingredients.seasoning"),
      ],
      instructions: [
        t("recipes.risotto.instructions.step1"),
        t("recipes.risotto.instructions.step2"),
        t("recipes.risotto.instructions.step3"),
        t("recipes.risotto.instructions.step4"),
        t("recipes.risotto.instructions.step5"),
        t("recipes.risotto.instructions.step6"),
        t("recipes.risotto.instructions.step7"),
        t("recipes.risotto.instructions.step8"),
        t("recipes.risotto.instructions.step9"),
      ],
      nutrition: {
        calories: 420,
        protein: "28g",
        carbs: "45g",
        fat: "12g",
      },
    },
    {
      id: 2,
      title: t("recipes.quinoa.title"),
      description: t("recipes.quinoa.description"),
      image:
        "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop&crop=center",
      time: t("recipes.quinoa.time"),
      servings: t("recipes.quinoa.servings"),
      difficulty: t("recipes.quinoa.difficulty"),
      tags: [
        t("recipes.tags.healthy"),
        t("recipes.tags.vegetarian"),
        t("recipes.tags.quick"),
      ],
      date: t("recipes.date.yesterday"),
      rating: 4,
      ingredients: [
        t("recipes.quinoa.ingredients.quinoa"),
        t("recipes.quinoa.ingredients.tomatoes"),
        t("recipes.quinoa.ingredients.cucumber"),
        t("recipes.quinoa.ingredients.feta"),
        t("recipes.quinoa.ingredients.olives"),
        t("recipes.quinoa.ingredients.oil"),
        t("recipes.quinoa.ingredients.lemon"),
        t("recipes.quinoa.ingredients.oregano"),
      ],
      instructions: [
        t("recipes.quinoa.instructions.step1"),
        t("recipes.quinoa.instructions.step2"),
        t("recipes.quinoa.instructions.step3"),
        t("recipes.quinoa.instructions.step4"),
        t("recipes.quinoa.instructions.step5"),
      ],
    },
    {
      id: 3,
      title: t("recipes.salmon.title"),
      description: t("recipes.salmon.description"),
      image:
        "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop&crop=center",
      time: t("recipes.salmon.time"),
      servings: t("recipes.salmon.servings"),
      difficulty: t("recipes.salmon.difficulty"),
      tags: [
        t("recipes.tags.fish"),
        t("recipes.tags.healthy"),
        t("recipes.tags.protein"),
      ],
      date: t("recipes.date.two_days"),
      rating: 5,
      ingredients: [
        t("recipes.salmon.ingredients.salmon"),
        t("recipes.salmon.ingredients.asparagus"),
        t("recipes.salmon.ingredients.lemons"),
        t("recipes.salmon.ingredients.oil"),
        t("recipes.salmon.ingredients.garlic"),
        t("recipes.salmon.ingredients.seasoning"),
      ],
      instructions: [
        t("recipes.salmon.instructions.step1"),
        t("recipes.salmon.instructions.step2"),
        t("recipes.salmon.instructions.step3"),
        t("recipes.salmon.instructions.step4"),
      ],
    },
    {
      id: 4,
      title: t("recipes.brownie.title"),
      description: t("recipes.brownie.description"),
      image:
        "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=300&fit=crop&crop=center",
      time: t("recipes.brownie.time"),
      servings: t("recipes.brownie.servings"),
      difficulty: t("recipes.brownie.difficulty"),
      tags: [
        t("recipes.tags.vegan"),
        t("recipes.tags.dessert"),
        t("recipes.tags.chocolate"),
      ],
      date: t("recipes.date.three_days"),
      rating: 4,
      ingredients: [
        t("recipes.brownie.ingredients.chocolate"),
        t("recipes.brownie.ingredients.sugar"),
        t("recipes.brownie.ingredients.flour"),
        t("recipes.brownie.ingredients.cocoa"),
        t("recipes.brownie.ingredients.oil"),
        t("recipes.brownie.ingredients.vanilla"),
        t("recipes.brownie.ingredients.salt"),
      ],
      instructions: [
        t("recipes.brownie.instructions.step1"),
        t("recipes.brownie.instructions.step2"),
        t("recipes.brownie.instructions.step3"),
        t("recipes.brownie.instructions.step4"),
        t("recipes.brownie.instructions.step5"),
      ],
    },
    {
      id: 5,
      title: t("recipes.pasta.title"),
      description: t("recipes.pasta.description"),
      image:
        "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400&h=300&fit=crop&crop=center",
      time: t("recipes.pasta.time"),
      servings: t("recipes.pasta.servings"),
      difficulty: t("recipes.pasta.difficulty"),
      tags: [
        t("recipes.tags.italian"),
        t("recipes.tags.quick"),
        t("recipes.tags.vegetarian"),
      ],
      date: t("recipes.date.week_ago"),
      rating: 5,
      ingredients: [
        t("recipes.pasta.ingredients.pasta"),
        t("recipes.pasta.ingredients.tomatoes"),
        t("recipes.pasta.ingredients.basil"),
        t("recipes.pasta.ingredients.garlic"),
        t("recipes.pasta.ingredients.oil"),
        t("recipes.pasta.ingredients.parmesan"),
        t("recipes.pasta.ingredients.seasoning"),
      ],
      instructions: [
        t("recipes.pasta.instructions.step1"),
        t("recipes.pasta.instructions.step2"),
        t("recipes.pasta.instructions.step3"),
        t("recipes.pasta.instructions.step4"),
        t("recipes.pasta.instructions.step5"),
      ],
    },
    {
      id: 6,
      title: t("recipes.soup.title"),
      description: t("recipes.soup.description"),
      image:
        "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop&crop=center",
      time: t("recipes.soup.time"),
      servings: t("recipes.soup.servings"),
      difficulty: t("recipes.soup.difficulty"),
      tags: [
        t("recipes.tags.healthy"),
        t("recipes.tags.vegetarian"),
        t("recipes.tags.comfort"),
      ],
      date: t("recipes.date.two_weeks"),
      rating: 4,
      ingredients: [
        t("recipes.soup.ingredients.vegetables"),
        t("recipes.soup.ingredients.broth"),
        t("recipes.soup.ingredients.onion"),
        t("recipes.soup.ingredients.garlic"),
        t("recipes.soup.ingredients.herbs"),
        t("recipes.soup.ingredients.seasoning"),
      ],
      instructions: [
        t("recipes.soup.instructions.step1"),
        t("recipes.soup.instructions.step2"),
        t("recipes.soup.instructions.step3"),
        t("recipes.soup.instructions.step4"),
      ],
    },
  ];

  return { recipes };
}
